[build]
  command = "npm install && npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20.0.0"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"
  
[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Compression and caching
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Encoding = "br"
    Content-Type = "application/javascript; charset=utf-8"
    Vary = "Accept-Encoding"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Encoding = "br"
    Content-Type = "text/css; charset=utf-8"
    Vary = "Accept-Encoding"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Encoding = "br"
    Content-Type = "text/html; charset=utf-8"
    Vary = "Accept-Encoding"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;"
    
[context.production.environment]
  NODE_ENV = "production"
  
[context.deploy-preview]
  command = "npm install && npm run build"
  
[context.branch-deploy]
  command = "npm install && npm run build"
