[build]
  command = "npm install && npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20.0.0"
  NPM_FLAGS = "--version"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
