[build]
  command = "npm install && npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20.0.0"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"
  
[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
[context.production.environment]
  NODE_ENV = "production"
  
[context.deploy-preview]
  command = "npm install && npm run build"
  
[context.branch-deploy]
  command = "npm install && npm run build"
