[build]
  command = "npm ci --include=dev && npx vite build"
  publish = "dist"
  environment = { NODE_VERSION = "18" }
  
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"  # Changed from boolean to string

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;"

[context.production]
  command = "npm install && npm run build"
  [context.production.environment]
    NODE_ENV = "production"

[context.deploy-preview]
  command = "npm install && npm run build"
  [context.deploy-preview.environment]
    NODE_ENV = "development"

[context.branch-deploy]
  command = "npm install && npm run build"
  [context.branch-deploy.environment]
    NODE_ENV = "development"
