// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjmfjpqkrwwqlxvzlycu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqbWZqcHFrcnd3cWx4dnpseWN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNjc0NjIsImV4cCI6MjA3MTc0MzQ2Mn0.XhxfmNRxKtRVWEfqFZkQM6VZ4UQ60It2y7Ze-J48mrE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});